version: '2'

services:

    main:
        image: puffinrocks/nginx-proxy
        volumes: 
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - "80:80"
        networks:
            - front
        tmpfs:
            - /run
            - /tmp

networks:
    front:
        external:
            name: "puffin_front"
