version: '2'

services:

    main:
        image: puffinrocks/proxy
        container_name: puffinxxxxproxy_main_1
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs_data:/etc/nginx/certs:ro
            - vhost_data:/etc/nginx/vhost.d
            - html_data:/usr/share/nginx/html
        ports:
            - "80:80"
            - "443:443"
        networks:
            - front
        tmpfs:
            - /run
            - /tmp

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs_data:/etc/nginx/certs
            - vhost_data:/etc/nginx/vhost.d
            - html_data:/usr/share/nginx/html
        environment:
            - NGINX_PROXY_CONTAINER=puffinxxxxproxy_main_1
            - ACME_TOS_HASH=cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b

volumes:
    certs_data:
    vhost_data:
    html_data:

networks:
    front:
        external:
            name: "puffin_front"
