version: '2'

services:

    main:
        image: loomchild/nginx-proxy
        volumes: 
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - "80:80"
        networks:
            - front

networks:
    front:
        external:
            name: "puffin_front"
