version: '2'

services:

    main:
        image: puffinrocks/proxy
        container_name: puffinxproxy_main_1
        volumes: 
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs_data:/etc/nginx/certs:ro
            - vhost_data:/etc/nginx/vhost.d
            - html_data:/usr/share/nginx/html
        ports:
            - "80:80"
            - "443:443"
        networks:
            - front
        tmpfs:
            - /run
            - /tmp

    letsencrypt:
        image: puffinrocks/letsencrypt-nginx-proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs_data:/etc/nginx/certs
            - vhost_data:/etc/nginx/vhost.d
            - html_data:/usr/share/nginx/html
        environment:
            - NGINX_PROXY_CONTAINER=puffinxproxy_main_1

volumes:
    certs_data:
    vhost_data:
    html_data:

networks:
    front:
        external:
            name: "puffin_front"
